import cgi

data=cgi.FieldStorage()

make=data.getvalue('make')
model=data.getvalue('model')
comment=data.getvalue('comment')

print("Content-type:text/html\r\n\r\n")
print("<!DOCTYPE HTML>")
print('<html>')
print('<html lang="en">')
print('<head>')
print('<title>Inquiries</title>')
print('<!--[if IE]>')
print('<script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>')
print('<![endif]-->')
print('<meta name="viewport" content="width=device-width, initial-scale=1">')
print('<link rel="stylesheet" href="css/bootstrap.min.css">')
print('<meta charset="UTF-8">')
print('<link rel="stylesheet" type="text/css" href="stylesheet.css">')
print('<link rel="icon" type="image/png" href="images/favicon.png" />')
print('</head>')
print('<body>')
print('<div id="wrapper">')
print('<div id="bg">')

print('<header>')
print('<div id="logo" style="background-image: url(logo.png)">')
print('</div>')
print('<div class="navi"><a href="index.html"><h1>Home</h1></a></div>')
print('<div class="navi"><a href="carspecs.html"><h1>House Details</h1></a></div>')
print('<div class="navi"><a href="gallery.html"><h1>Gallery</h1></a></div>')
print('<div class="navi"><a href="inquiries.html"><h1>Inquiries</h1></a></div>')
print('</header>')
print('<div id="content2">')
print("<h1>Response:</h1>")
print('<section>')
print('<br><p> Thanks for this comment ',make,' ...</p></br>')
print('<br><P> <i> ',comment,' </i> </p></br>')
print('<P> We will report to ',model,' </p>')
print('</section>')
print('</div>')
print('<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>')
print('<script src="js/bootstrap.min.js"></script>')

print('<footer>')
print('</footer>')
print('</div>')
print('</div>')
print('</body>')
print('</html>')

f=open("data.txt", 'a')
f.write("Client Name: "+make+"\n\n")
f.write("Client Email: "+model+"\n\n")
f.write("Comment: "+comment+"\n\n\n\n")
f.close()


